# Generated by Django 2.2.7 on 2019-11-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191110_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
